# Generated by Django 4.2.16 on 2024-11-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_osoba_wlasciciel_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': [('can_view_other_persons', 'Pozwala wyświetlać obiekty modelu Osoba, których użytkownik nie jest właścicielem.')]},
        ),
    ]
